rabbitmq:
  host: 10.8.38.21
  port: 5672

devices:
  thermistors:
    host: 10.8.38.180
    port: 1025
    channels:
      supply: 7
      r1: 8
      b1: 9
      z1: 6
      r3: 10
      b3: 11
      z3: 12
      r2: 13
      b2: 14
      z2: 15

  ion:
    - host: 10.8.38.157
      port: 502
      cameras:
        z1:
          signal_address: 0
          on_off_address: 2020
        b1:
          signal_address: 2
          on_off_address: 2021
        r1:
          signal_address: 4
          on_off_address: 2022
    - host: 10.8.38.155
      port: 502
      cameras:
        z2:
          signal_address: 0
          on_off_address: 2020
        b2:
          signal_address: 2
          on_off_address: 2021
        r2:
          signal_address: 4
          on_off_address: 2022
    - host: 10.8.38.156
      port: 502
      cameras:
        z3:
          signal_address: 0
          on_off_address: 2020
        b3:
          signal_address: 2
          on_off_address: 2021
        r3:
          signal_address: 4
          on_off_address: 2022
